# Используем базовый образ nginx
FROM nginx:alpine

# Копируем содержимое папки frontend в директорию, обслуживаемую nginx
COPY . /usr/share/nginx/html

# Порт, на котором будет доступен фронтенд
EXPOSE 80
